# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_line.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_subwindow(object):
    def setupUi(self, subwindow):
        subwindow.setObjectName("subwindow")
        subwindow.resize(902, 438)
        self.verticalLayout = QtWidgets.QVBoxLayout(subwindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_67 = QtWidgets.QLabel(subwindow)
        self.label_67.setText("")
        self.label_67.setObjectName("label_67")
        self.gridLayout.addWidget(self.label_67, 11, 3, 1, 1)
        self.label_62 = QtWidgets.QLabel(subwindow)
        self.label_62.setObjectName("label_62")
        self.gridLayout.addWidget(self.label_62, 5, 3, 1, 1)
        self.label_60 = QtWidgets.QLabel(subwindow)
        self.label_60.setObjectName("label_60")
        self.gridLayout.addWidget(self.label_60, 4, 3, 1, 1)
        self.label_47 = QtWidgets.QLabel(subwindow)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 6, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(subwindow)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(subwindow)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(subwindow)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(subwindow)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(subwindow)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(subwindow)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 1, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(subwindow)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(subwindow)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 11, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(subwindow)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(subwindow)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(subwindow)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 10, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(subwindow)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(subwindow)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 12, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(subwindow)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 13, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(subwindow)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 14, 0, 1, 1)
        self.label = QtWidgets.QLabel(subwindow)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(subwindow)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 15, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(subwindow)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 9, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(subwindow)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 13, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(subwindow)
        self.label_49.setObjectName("label_49")
        self.gridLayout.addWidget(self.label_49, 13, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(subwindow)
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 12, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(subwindow)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 9, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(subwindow)
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 11, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(subwindow)
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 14, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(subwindow)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 15, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(subwindow)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 5, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(subwindow)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 8, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(subwindow)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(subwindow)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(subwindow)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 3, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(subwindow)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 3, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(subwindow)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 4, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(subwindow)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 10, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(subwindow)
        self.label_64.setObjectName("label_64")
        self.gridLayout.addWidget(self.label_64, 14, 3, 1, 1)
        self.label_35 = QtWidgets.QLabel(subwindow)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 4, 2, 1, 1)
        self.label_63 = QtWidgets.QLabel(subwindow)
        self.label_63.setObjectName("label_63")
        self.gridLayout.addWidget(self.label_63, 15, 3, 1, 1)
        self.label_65 = QtWidgets.QLabel(subwindow)
        self.label_65.setObjectName("label_65")
        self.gridLayout.addWidget(self.label_65, 12, 3, 1, 1)
        self.label_40 = QtWidgets.QLabel(subwindow)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 14, 1, 1, 1)
        self.label_66 = QtWidgets.QLabel(subwindow)
        self.label_66.setObjectName("label_66")
        self.gridLayout.addWidget(self.label_66, 13, 3, 1, 1)
        self.label_52 = QtWidgets.QLabel(subwindow)
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 12, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(subwindow)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 10, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(subwindow)
        self.label_51.setObjectName("label_51")
        self.gridLayout.addWidget(self.label_51, 5, 2, 1, 1)
        self.label_55 = QtWidgets.QLabel(subwindow)
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 11, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(subwindow)
        self.label_46.setObjectName("label_46")
        self.gridLayout.addWidget(self.label_46, 7, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(subwindow)
        self.label_45.setObjectName("label_45")
        self.gridLayout.addWidget(self.label_45, 8, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(subwindow)
        self.label_48.setObjectName("label_48")
        self.gridLayout.addWidget(self.label_48, 15, 2, 1, 1)
        self.label_59 = QtWidgets.QLabel(subwindow)
        self.label_59.setObjectName("label_59")
        self.gridLayout.addWidget(self.label_59, 6, 3, 1, 1)
        self.label_54 = QtWidgets.QLabel(subwindow)
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 8, 3, 1, 1)
        self.label_50 = QtWidgets.QLabel(subwindow)
        self.label_50.setObjectName("label_50")
        self.gridLayout.addWidget(self.label_50, 9, 3, 1, 1)
        self.label_58 = QtWidgets.QLabel(subwindow)
        self.label_58.setObjectName("label_58")
        self.gridLayout.addWidget(self.label_58, 7, 3, 1, 1)
        self.label_57 = QtWidgets.QLabel(subwindow)
        self.label_57.setObjectName("label_57")
        self.gridLayout.addWidget(self.label_57, 10, 3, 1, 1)
        self.line = QtWidgets.QFrame(subwindow)
        self.line.setLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 4)
        self.line_2 = QtWidgets.QFrame(subwindow)
        self.line_2.setLineWidth(10)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 0, 1, 4)
        self.label_61 = QtWidgets.QLabel(subwindow)
        self.label_61.setObjectName("label_61")
        self.gridLayout.addWidget(self.label_61, 3, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(subwindow)
        self.line_3.setLineWidth(10)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 16, 0, 1, 4)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(subwindow)
        QtCore.QMetaObject.connectSlotsByName(subwindow)

    def retranslateUi(self, subwindow):
        _translate = QtCore.QCoreApplication.translate
        subwindow.setWindowTitle(_translate("subwindow", "Form"))
        self.label_62.setText(_translate("subwindow", "Goose-neck light guide 1500 ECO + focusing attachment (ZEISS) + CL6000 (ZEISS)"))
        self.label_60.setText(_translate("subwindow", "C-PLUS RECT-28 (COMET)"))
        self.label_47.setText(_translate("subwindow", "Goose-neck +CL9000"))
        self.label_4.setText(_translate("subwindow", "GN9000"))
        self.label_3.setText(_translate("subwindow", "RL6000"))
        self.label_25.setText(_translate("subwindow", "略称"))
        self.label_5.setText(_translate("subwindow", "GN6000"))
        self.label_6.setText(_translate("subwindow", "PB"))
        self.label_28.setText(_translate("subwindow", "製品名＋光源"))
        self.label_9.setText(_translate("subwindow", "RL9000"))
        self.label_10.setText(_translate("subwindow", "REF"))
        self.label_27.setText(_translate("subwindow", "照明呼称"))
        self.label_8.setText(_translate("subwindow", "RLS"))
        self.label_11.setText(_translate("subwindow", "RLL"))
        self.label_26.setText(_translate("subwindow", "波長"))
        self.label_7.setText(_translate("subwindow", "HP-365"))
        self.label_22.setText(_translate("subwindow", "SP365"))
        self.label_23.setText(_translate("subwindow", "SP530"))
        self.label.setText(_translate("subwindow", "PA"))
        self.label_24.setText(_translate("subwindow", "SP590"))
        self.label_30.setText(_translate("subwindow", "Ring light (Schott)"))
        self.label_43.setText(_translate("subwindow", "uv 365nm"))
        self.label_49.setText(_translate("subwindow", "Spot 365 nm"))
        self.label_37.setText(_translate("subwindow", "uv 365nm"))
        self.label_42.setText(_translate("subwindow", "wl"))
        self.label_53.setText(_translate("subwindow", "Spot 530 nm"))
        self.label_38.setText(_translate("subwindow", "uv 590nm"))
        self.label_32.setText(_translate("subwindow", "wl"))
        self.label_31.setText(_translate("subwindow", "wl"))
        self.label_33.setText(_translate("subwindow", "wl"))
        self.label_2.setText(_translate("subwindow", "wl"))
        self.label_36.setText(_translate("subwindow", "Panel-type A"))
        self.label_34.setText(_translate("subwindow", "wl"))
        self.label_29.setText(_translate("subwindow", "wl"))
        self.label_39.setText(_translate("subwindow", "wl"))
        self.label_64.setText(_translate("subwindow", "LED530/L-STND (OptoCode)"))
        self.label_35.setText(_translate("subwindow", "Panel-type B"))
        self.label_63.setText(_translate("subwindow", "LED590/L-STND (OptoCode)"))
        self.label_65.setText(_translate("subwindow", "LED365-9UV033B (OptoCode)"))
        self.label_40.setText(_translate("subwindow", "uv 530nm"))
        self.label_66.setText(_translate("subwindow", "LED365/L-STND (OptoCode)"))
        self.label_52.setText(_translate("subwindow", "UV-high-power 365 nm"))
        self.label_44.setText(_translate("subwindow", "Ring light (LAOWA)"))
        self.label_51.setText(_translate("subwindow", "Goose-neck + CL6000"))
        self.label_55.setText(_translate("subwindow", "Reflecter"))
        self.label_46.setText(_translate("subwindow", "Ring light (ZEISS) + CL6000"))
        self.label_45.setText(_translate("subwindow", "Ring light (ZEISS) + CL9000"))
        self.label_48.setText(_translate("subwindow", "Spot 590 nm"))
        self.label_59.setText(_translate("subwindow", "Goose-neck light guide 1500 ECO + focusing attachment (ZEISS) + CL9000 (ZEISS)"))
        self.label_54.setText(_translate("subwindow", "Slit-ring illuminator 1500 ECO (ZEISS) + CL9000 (ZEISS)"))
        self.label_50.setText(_translate("subwindow", "Easy LED ring light (SCHOTT AG)"))
        self.label_58.setText(_translate("subwindow", "Slit-ring illuminator 1500 ECO (ZEISS) + CL6000 (ZEISS)"))
        self.label_57.setText(_translate("subwindow", "Front LED Ring Light of Laowa 25mm f/2.8 2.5-5X Ultra-Macro (LAOWA)"))
        self.label_61.setText(_translate("subwindow", "C-PLUS RECT-20 (COMET)"))

